import {
  mysqlTable,
  serial,
  varchar,
  text,
  timestamp,
  json,
  decimal,
  int,
  mysqlEnum,
} from "drizzle-orm/mysql-core";

export const studentProfiles = mysqlTable("student_profiles", {
  id: serial("id").primaryKey(),
  fullName: varchar("full_name", { length: 255 }).notNull(),
  email: varchar("email", { length: 255 }).notNull(),
  degreeProgram: varchar("degree_program", { length: 255 }).notNull(),
  semester: varchar("semester", { length: 50 }).notNull(),
  cgpa: decimal("cgpa", { precision: 3, scale: 2 }),
  skills: text("skills"),
  interests: text("interests"),
  preferredOpportunityTypes: text("preferred_opportunity_types"),
  financialNeed: mysqlEnum("financial_need", ["yes", "no", "partial"]).default("no"),
  locationPreference: varchar("location_preference", { length: 255 }),
  pastExperience: text("past_experience"),
  languages: text("languages"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const emailAnalyses = mysqlTable("email_analyses", {
  id: serial("id").primaryKey(),
  rawEmail: text("raw_email").notNull(),
  subject: text("subject"),
  sender: text("sender"),
  isOpportunity: mysqlEnum("is_opportunity", ["yes", "no", "uncertain"]).default("uncertain"),
  confidence: decimal("confidence", { precision: 4, scale: 3 }),
  category: varchar("category", { length: 100 }),
  extractedData: json("extracted_data"),
  processingStatus: mysqlEnum("processing_status", ["pending", "processing", "completed", "failed"]).default("pending"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const opportunities = mysqlTable("opportunities", {
  id: serial("id").primaryKey(),
  emailAnalysisId: int("email_analysis_id"),
  studentProfileId: int("student_profile_id"),
  title: text("title").notNull(),
  organization: varchar("organization", { length: 255 }),
  opportunityType: varchar("opportunity_type", { length: 100 }).notNull(),
  category: varchar("category", { length: 100 }),
  description: text("description"),
  deadline: varchar("deadline", { length: 255 }),
  deadlineTimestamp: timestamp("deadline_timestamp"),
  eligibilityCriteria: json("eligibility_criteria"),
  requiredDocuments: json("required_documents"),
  applicationLink: text("application_link"),
  contactEmail: varchar("contact_email", { length: 255 }),
  contactPhone: varchar("contact_phone", { length: 50 }),
  benefits: json("benefits"),
  location: varchar("location", { length: 255 }),
  isRemote: mysqlEnum("is_remote", ["yes", "no", "hybrid"]).default("no"),
  stipend: varchar("stipend", { length: 255 }),
  duration: varchar("duration", { length: 255 }),
  relevanceScore: decimal("relevance_score", { precision: 5, scale: 2 }),
  urgencyScore: decimal("urgency_score", { precision: 5, scale: 2 }),
  completenessScore: decimal("completeness_score", { precision: 5, scale: 2 }),
  overallScore: decimal("overall_score", { precision: 5, scale: 2 }),
  rankingReason: text("ranking_reason"),
  fitAnalysis: json("fit_analysis"),
  actionItems: json("action_items"),
  urgencyLevel: mysqlEnum("urgency_level", ["critical", "high", "medium", "low"]).default("medium"),
  daysUntilDeadline: int("days_until_deadline"),
  status: mysqlEnum("status", ["open", "expired", "applied", "saved"]).default("open"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
